/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LanguageChar125IndexRouteImport } from './routes/{-$language}/index'
import { Route as Char123LanguageChar125DocsRouteImport } from './routes/{-$language}/docs'
import { Route as Char123LanguageChar125ComponentsRouteImport } from './routes/{-$language}/components'

const Char123LanguageChar125IndexRoute =
  Char123LanguageChar125IndexRouteImport.update({
    id: '/{-$language}/',
    path: '/{-$language}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LanguageChar125DocsRoute =
  Char123LanguageChar125DocsRouteImport.update({
    id: '/{-$language}/docs',
    path: '/{-$language}/docs',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LanguageChar125ComponentsRoute =
  Char123LanguageChar125ComponentsRouteImport.update({
    id: '/{-$language}/components',
    path: '/{-$language}/components',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$language}/components': typeof Char123LanguageChar125ComponentsRoute
  '/{-$language}/docs': typeof Char123LanguageChar125DocsRoute
  '/{-$language}/': typeof Char123LanguageChar125IndexRoute
}
export interface FileRoutesByTo {
  '/{-$language}/components': typeof Char123LanguageChar125ComponentsRoute
  '/{-$language}/docs': typeof Char123LanguageChar125DocsRoute
  '/{-$language}': typeof Char123LanguageChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$language}/components': typeof Char123LanguageChar125ComponentsRoute
  '/{-$language}/docs': typeof Char123LanguageChar125DocsRoute
  '/{-$language}/': typeof Char123LanguageChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$language}/components'
    | '/{-$language}/docs'
    | '/{-$language}/'
  fileRoutesByTo: FileRoutesByTo
  to: '/{-$language}/components' | '/{-$language}/docs' | '/{-$language}'
  id:
    | '__root__'
    | '/{-$language}/components'
    | '/{-$language}/docs'
    | '/{-$language}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LanguageChar125ComponentsRoute: typeof Char123LanguageChar125ComponentsRoute
  Char123LanguageChar125DocsRoute: typeof Char123LanguageChar125DocsRoute
  Char123LanguageChar125IndexRoute: typeof Char123LanguageChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$language}/': {
      id: '/{-$language}/'
      path: '/{-$language}'
      fullPath: '/{-$language}/'
      preLoaderRoute: typeof Char123LanguageChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$language}/docs': {
      id: '/{-$language}/docs'
      path: '/{-$language}/docs'
      fullPath: '/{-$language}/docs'
      preLoaderRoute: typeof Char123LanguageChar125DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$language}/components': {
      id: '/{-$language}/components'
      path: '/{-$language}/components'
      fullPath: '/{-$language}/components'
      preLoaderRoute: typeof Char123LanguageChar125ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LanguageChar125ComponentsRoute: Char123LanguageChar125ComponentsRoute,
  Char123LanguageChar125DocsRoute: Char123LanguageChar125DocsRoute,
  Char123LanguageChar125IndexRoute: Char123LanguageChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
